### ISSUE TITLE
[Envoy-MG] JWT Authentication for envoy gateway

### ISSUE THREAD

**Issue by Rajith90** [wso2/product-microgateway#1447]
### Describe your problem(s)
Envoy gateway should allow to access APIs via trusted jwts issues by trusted key managers.
This jwt can be validated using the jwks as well as the public cert of the key manager. And also the self containing jwts should also be supported.

### Describe your solution
Implement an authentication filter in the filter chain side and plug the JWT validation authenticator.

### How will you implement it
Certificate validation as well as JWKS endpoind should also be supported.

#### Subtasks
- [x] [JWT Authentication] JMS and REST based Subscription data retrieval https://github.com/wso2/product-microgateway/issues/1461
- [x] Introduce a Config Model for Filter Chain https://github.com/wso2/product-microgateway/issues/1462
- [x] Implement Scope Validation for Envoy-mgw https://github.com/wso2/product-microgateway/issues/1463
- [x] Implement a cache for token validation #1643

---

**Comment by Rajith90** [comment]
All the sub tasks are completed
