### ISSUE TITLE
Virtual Hosts - (VHosts)

### ISSUE THREAD

**Issue by renuka-fernando** [wso2/product-microgateway#1725]
### Describe your problem(s)
Virtual Hosts enables users to expose APIs using different hostnames while serving gateway on a single server (or pool of servers).

### How will you implement it
- Replace unique identifier of internal memory maps with `<vhost>:<api_name>:<version>` and keep all routes, listeners with this new ID

### Tasks
- [x] Basic vhosts support - https://github.com/wso2/product-microgateway/issues/1877
- [ ] Integration Tests for Vhosts
- [x] Undeploy APIs with supporting `--gateway-env` flag from APICTL - https://github.com/wso2/product-apim-tooling/issues/681
- [x] Display vhosts when `apictl mg get apis` command executed - https://github.com/wso2/product-apim-tooling/issues/684
