### ISSUE TITLE
Add interceptor support

### ISSUE THREAD

**Issue by AmaliMatharaarachchi** [wso2/product-microgateway#2231]
### Describe your problem(s)

- [x] Add new extension for interceptors in swagger https://github.com/wso2/product-microgateway/issues/2232
- [x] Enable/disable interceptors (lua filter) per API/ per resource based on API definition https://github.com/wso2/product-microgateway/issues/2232
- [x] https://github.com/wso2/product-microgateway/issues/2233
- [x] https://github.com/wso2/product-microgateway/issues/2274
- [x] https://github.com/wso2/product-microgateway/issues/2298
- [x] Add dynamic endpoint support https://github.com/wso2/product-microgateway/issues/2236
  - [x] https://github.com/wso2/product-microgateway/issues/2329
- [x] https://github.com/wso2/product-microgateway/issues/2328
- [x] Define the swagger interface for interceptor service
- [x] https://github.com/wso2/product-microgateway/issues/2315
- [x] Samples
  - [x] https://github.com/wso2/product-microgateway/issues/2358
  - [x] Java, Go, Node - https://github.com/wso2/product-microgateway/issues/2405
- [x] Documentation -https://github.com/wso2/docs-apim/issues/4952
- [x] https://github.com/wso2/product-microgateway/issues/2433

### How will you implement it

---

**Comment by renuka-fernando** [comment]
Completed the task
